export const countries = ["Saudi Arabia", "outside Saudi Arabia "];
export const age = ["from 19 to 25", "from 26 to 45", "above 45"];
export const gender = ["male", "female"];
export const religion = ["Muslim", "non muslim"];

export const nationalities = [
  "Afghan",
  "Åland Islander",
  "Albanian",
  "Algerian",
  "American Samoan",
  "Andorran",
  "Angolan",
  "Anguillan",
  "Antarctican",
  "Antiguan and Barbudan",
  "Argentine",
  "Armenian",
  "Aruban",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bermudian",
  "Bhutanese",
  "Bolivian",
  "Bosnian and Herzegovinian",
  "Botswanan",
  "Bouvet Islander",
  "Brazilian",
  "British Indian Ocean Territory Citizen",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Caymanian",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Christmas Islander",
  "Cocos Islander",
  "Colombian",
  "Comoran",
  "Congolese",
  "Congolese (Democratic Republic)",
  "Cook Islander",
  "Costa Rican",
  "Ivorian",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Dominican (Republic)",
  "Ecuadorian",
  "Egyptian",
  "Salvadoran",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Falkland Islander",
  "Faroese",
  "Fijian",
  "Finnish",
  "French",
  "French Guianese",
  "French Polynesian",
  "French Southern Territories Citizen",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Gibraltarian",
  "Greek",
  "Greenlander",
  "Grenadian",
  "Guadeloupean",
  "Guamanian",
  "Guatemalan",
  "Channel Islander",
  "Guinean",
  "Bissau-Guinean",
  "Guyanese",
  "Haitian",
  "Heard Islander",
  "Vatican Citizen",
  "Honduran",
  "Hong Konger",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Manx",
  "Italian",
  "Jamaican",
  "Japanese",
  "Channel Islander",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "I-Kiribati",
  "North Korean",
  "South Korean",
  "Kuwaiti",
  "Kyrgyzstani",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Basotho",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourgish",
  "Macanese",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Martiniquais",
  "Mauritanian",
  "Mauritian",
  "Mahoran",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monégasque",
  "Mongolian",
  "Montenegrin",
  "Montserratian",
  "Moroccan",
  "Mozambican",
  "Myanmarese",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "Dutch",
  "Dutch Antillean",
  "New Caledonian",
  "New Zealander",
  "Nicaraguan",
  "Nigerien",
  "Nigerian",
  "Niuean",
  "Norfolk Islander",
  "Northern Marianan",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Palestinian",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Filipino",
  "Pitcairn Islander",
  "Polish",
  "Portuguese",
  "Puerto Rican",
  "Qatari",
  "Réunionese",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Helenian",
  "Kittitian and Nevisian",
  "Saint Lucian",
  "Saint-Pierrais",
  "Vincentian",
  "Samoan",
  "Sanmarinese",
  "Sao Tomean",
  "Saudi",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovak",
  "Slovene",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Georgian",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamese",
  "Svalbardian",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajikistani",
  "Tanzanian",
  "Thai",
  "Timorese",
  "Togolese",
  "Tokelauan",
  "Tongan",
  "Trinidadian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Turks and Caicos Islander",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Emirati",
  "British",
  "American",
  "American (Outlying Islands)",
  "Uruguayan",
  "Uzbekistani",
  "Ni-Vanuatu",
  "Venezuelan",
  "Vietnamese",
  "British Virgin Islander",
  "U.S. Virgin Islander",
  "Wallisian",
  "Sahrawi",
  "Yemeni",
  "Zambian",
  "Zimbabwean",
];
